### ISSUE TITLE
テスト10

### ISSUE THREAD

**Issue by SyuheyK** [SyuheyK/actions_test#107]
テストです

```yaml test
table_name: this_is_table_name
condition_string1: this_is_first_condition
condition1:
  condition_string2: this_is_second_condition
  column_names:
   - column_name1
   - column_name2
   - column_name3
condition2:
  condition_string2: this_is_third_condition
  column_names:
   - column_name1
   - column_name4
```
