### ISSUE TITLE
テスト4

### ISSUE THREAD

**Issue by SyuheyK** [SyuheyK/actions_test#18]
テストです

```yaml test
test1: 12
test2: "テスト2"
test3: true
test4: テスト4
```
