### ISSUE TITLE
テスト8

### ISSUE THREAD

**Issue by SyuheyK** [SyuheyK/actions_test#22]
テストです

```yaml test
test1: 
  test1_1: テストです
  test1_2: 
    - テスト1
    - テスト2
    - テスト3
test2: 
  test2_1: "テスト2"
  test2_2: true
  test2_3: null
```
